version: '3'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "5051:5051"
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules

  postgres:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/database-seed.sql
    container_name: my-postgres-container
